name: extensions_package
description: "Common extensions for Dart and Flutter for any project/app."
version: 0.0.2+1
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=3.24.1"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.7
  very_good_analysis: ^6.0.0

# Element of flutter_gen https://pub.dev/packages/flutter_gen/install
# '% dart pub global activate flutter_gen'
# '% fluttergen'
flutter_gen:
  line_length: 132

flutter:
  uses-material-design: true
  assets:
    - assets/images/
