# Melos - A tool for managing Dart & Flutter repositories with multiple packages
# https://pub.dev/packages/melos
# To install -> `dart pub global activate melos`

name: icodeforyou_package

packages:
  - . # top level directory
  - packages/* # everything in packages directory

ignore:
  - packages/*/example

# To use -> `melos run <script>`
scripts:
  analyze: melos exec -- "dart analyze ."
  build: melos exec -- "flutter pub run build_runner build --delete-conflicting-outputs"
  fix_preview: melos exec -- "dart fix --dry-run"
  fix: melos exec -- "dart fix --apply"
  format: melos exec -- "dart format ."
  get: melos exec -- "flutter pub get"
  lint: melos run format && melos run analyze
  test:
    run: flutter test
    description: Run all tests
  upgrade_major: melos exec -- "flutter pub upgrade --major-versions"
  upgrade: melos exec -- "flutter pub upgrade"

# Other commands:
#   bootstrap   Link local packages
#   clean       Clean this workspace and all packages {melos bootstrap will be required after this}
#   exec        Execute an arbitrary command in each package
#   list        List local packages in various output formats
#   --help      Show list of commands